
package com.clevel.selos.integration.brms.service.document.apprisalrules;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DecisionServiceSE_Document_Appraisal_Flow", targetNamespace = "http://www.ilog.com/rules/DecisionService", wsdlLocation = "file:/C:/Users/Chai/Desktop/BRMS_WSDL/6.wsdl")
public class DecisionServiceSEDocumentAppraisalFlow_Service
    extends Service
{

    private final static URL DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_WSDL_LOCATION;
    private final static WebServiceException DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_EXCEPTION;
    private final static QName DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_QNAME = new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSE_Document_Appraisal_Flow");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://stmbrmsred1:9080/DecisionService/ws/SE_Document_Appraisal_RuleApp/1.0/SE_Document_Appraisal_Flow?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_WSDL_LOCATION = url;
        DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_EXCEPTION = e;
    }

    public DecisionServiceSEDocumentAppraisalFlow_Service() {
        super(__getWsdlLocation(), DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_QNAME);
    }

    public DecisionServiceSEDocumentAppraisalFlow_Service(URL wsdlLocation) {
        super(wsdlLocation, DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_QNAME);
    }


    public DecisionServiceSEDocumentAppraisalFlow_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DecisionServiceSEDocumentAppraisalFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEDocumentAppraisalFlow getDecisionServiceSOAPstmbrmsred1() {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEDocumentAppraisalFlow.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DecisionServiceSEDocumentAppraisalFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEDocumentAppraisalFlow getDecisionServiceSOAPstmbrmsred1(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEDocumentAppraisalFlow.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_EXCEPTION!= null) {
            throw DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_EXCEPTION;
        }
        return DECISIONSERVICESEDOCUMENTAPPRAISALFLOW_WSDL_LOCATION;
    }

}
