
package com.ilog.rules.decisionservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DecisionServiceException", targetNamespace = "http://www.ilog.com/rules/DecisionService")
public class DecisionServiceSoapFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DecisionServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DecisionServiceSoapFault(String message, DecisionServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DecisionServiceSoapFault(String message, DecisionServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ilog.rules.decisionservice.DecisionServiceException
     */
    public DecisionServiceException getFaultInfo() {
        return faultInfo;
    }

}
