
package com.clevel.selos.integration.brms.service.prescreenunderwritingrules;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */

@WebServiceClient(name = "DecisionServiceSE_Prescreen_UWS_Flow", targetNamespace = "http://www.ilog.com/rules/DecisionService", wsdlLocation = "http://stmbrmsred1:9080/DecisionService/ws/SE_Prescreen_UWS_RuleApp/1.0/SE_Prescreen_UWS_Flow?WSDL")
public class DecisionServiceSEPrescreenUWSFlow_Service
        extends Service {

    private final static URL DECISIONSERVICESEPRESCREENUWSFLOW_WSDL_LOCATION;
    private final static WebServiceException DECISIONSERVICESEPRESCREENUWSFLOW_EXCEPTION;
    private final static QName DECISIONSERVICESEPRESCREENUWSFLOW_QNAME = new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSE_Prescreen_UWS_Flow");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://stmbrmsred1:9080/DecisionService/ws/SE_Prescreen_UWS_RuleApp/1.0/SE_Prescreen_UWS_Flow?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DECISIONSERVICESEPRESCREENUWSFLOW_WSDL_LOCATION = url;
        DECISIONSERVICESEPRESCREENUWSFLOW_EXCEPTION = e;
    }

    public DecisionServiceSEPrescreenUWSFlow_Service() {
        super(__getWsdlLocation(), DECISIONSERVICESEPRESCREENUWSFLOW_QNAME);
    }

    public DecisionServiceSEPrescreenUWSFlow_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DECISIONSERVICESEPRESCREENUWSFLOW_QNAME);
    }

    public DecisionServiceSEPrescreenUWSFlow_Service(URL wsdlLocation) {
        super(wsdlLocation, DECISIONSERVICESEPRESCREENUWSFLOW_QNAME);
    }

    public DecisionServiceSEPrescreenUWSFlow_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DECISIONSERVICESEPRESCREENUWSFLOW_QNAME);
    }

    public DecisionServiceSEPrescreenUWSFlow_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DecisionServiceSEPrescreenUWSFlow_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns DecisionServiceSEPrescreenUWSFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEPrescreenUWSFlow getDecisionServiceSOAPstmbrmsred1() {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEPrescreenUWSFlow.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DecisionServiceSEPrescreenUWSFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEPrescreenUWSFlow getDecisionServiceSOAPstmbrmsred1(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEPrescreenUWSFlow.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DECISIONSERVICESEPRESCREENUWSFLOW_EXCEPTION != null) {
            throw DECISIONSERVICESEPRESCREENUWSFLOW_EXCEPTION;
        }
        return DECISIONSERVICESEPRESCREENUWSFLOW_WSDL_LOCATION;
    }

}
