
package com.tmb.common.data.eaicalrisknewpersonal;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "EAICalRiskNewPersonal", targetNamespace = "http://data.common.tmb.com/EAICalRiskNewPersonal/", wsdlLocation = "file:/C:/Users/Demo/Desktop/wsdl/EAICalRiskNewPersonal.wsdl")
public class EAICalRiskNewPersonal_Service
        extends Service {

    private final static URL EAICALRISKNEWPERSONAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.tmb.common.data.eaicalrisknewpersonal.EAICalRiskNewPersonal_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.tmb.common.data.eaicalrisknewpersonal.EAICalRiskNewPersonal_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Demo/Desktop/wsdl/EAICalRiskNewPersonal.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Demo/Desktop/wsdl/EAICalRiskNewPersonal.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EAICALRISKNEWPERSONAL_WSDL_LOCATION = url;
    }

    public EAICalRiskNewPersonal_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EAICalRiskNewPersonal_Service() {
        super(EAICALRISKNEWPERSONAL_WSDL_LOCATION, new QName("http://data.common.tmb.com/EAICalRiskNewPersonal/", "EAICalRiskNewPersonal"));
    }

    /**
     * @return returns EAICalRiskNewPersonal
     */
    @WebEndpoint(name = "EAICalRiskNewPersonal")
    public EAICalRiskNewPersonal getEAICalRiskNewPersonal() {
        return super.getPort(new QName("http://data.common.tmb.com/EAICalRiskNewPersonal/", "EAICalRiskNewPersonal"), EAICalRiskNewPersonal.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns EAICalRiskNewPersonal
     */
    @WebEndpoint(name = "EAICalRiskNewPersonal")
    public EAICalRiskNewPersonal getEAICalRiskNewPersonal(WebServiceFeature... features) {
        return super.getPort(new QName("http://data.common.tmb.com/EAICalRiskNewPersonal/", "EAICalRiskNewPersonal"), EAICalRiskNewPersonal.class, features);
    }

}
