
package com.tmb.common.data.eaisearchindividualcustomercm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "EAISearchIndividualCustomerCM", targetNamespace = "http://data.common.tmb.com/EAISearchIndividualCustomerCM/", wsdlLocation = "file:/C:/Users/sahawat/Desktop/ssssssss/EAISearchIndividualCustomerCM.wsdl")
public class EAISearchIndividualCustomerCM_Service
    extends Service
{

    private final static URL EAISEARCHINDIVIDUALCUSTOMERCM_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.tmb.common.data.eaisearchindividualcustomercm.EAISearchIndividualCustomerCM_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.tmb.common.data.eaisearchindividualcustomercm.EAISearchIndividualCustomerCM_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/sahawat/Desktop/ssssssss/EAISearchIndividualCustomerCM.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/sahawat/Desktop/ssssssss/EAISearchIndividualCustomerCM.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EAISEARCHINDIVIDUALCUSTOMERCM_WSDL_LOCATION = url;
    }

    public EAISearchIndividualCustomerCM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EAISearchIndividualCustomerCM_Service() {
        super(EAISEARCHINDIVIDUALCUSTOMERCM_WSDL_LOCATION, new QName("http://data.common.tmb.com/EAISearchIndividualCustomerCM/", "EAISearchIndividualCustomerCM"));
    }

    /**
     * 
     * @return
     *     returns EAISearchIndividualCustomerCM
     */
    @WebEndpoint(name = "EAISearchIndividualCustomerCM")
    public EAISearchIndividualCustomerCM getEAISearchIndividualCustomerCM() {
        return super.getPort(new QName("http://data.common.tmb.com/EAISearchIndividualCustomerCM/", "EAISearchIndividualCustomerCM"), EAISearchIndividualCustomerCM.class);
    }

}
