
package com.tmb.sme.data.eaisearchindividualcustomer;

import javax.jws.*;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.tmb.sme.data.requestsearchindividualcustomer.ReqSearchIndividualCustomer;
import com.tmb.sme.data.responsesearchindividualcustomer.ResSearchIndividualCustomer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EAISearchIndividualCustomer", targetNamespace = "http://data.sme.tmb.com/EAISearchIndividualCustomer/")
public interface EAISearchIndividualCustomer {


    /**
     * 
     * @param requestData
     * @return
     *     returns com.tmb.sme.data.responsesearchindividualcustomer.ResSearchIndividualCustomer
     */
    @WebMethod(action = "searchIndividualCustomer")
    @WebResult(name = "responseData", targetNamespace = "")
    @RequestWrapper(localName = "searchIndividualCustomer", targetNamespace = "http://data.sme.tmb.com/EAISearchIndividualCustomer/", className = "com.tmb.sme.data.eaisearchindividualcustomer.SearchIndividualCustomer")
    @ResponseWrapper(localName = "searchIndividualCustomerResponse", targetNamespace = "http://data.sme.tmb.com/EAISearchIndividualCustomer/", className = "com.tmb.sme.data.eaisearchindividualcustomer.SearchIndividualCustomerResponse")
    public ResSearchIndividualCustomer searchIndividualCustomer(@WebParam(name = "requestData", targetNamespace = "")
        ReqSearchIndividualCustomer requestData);

}
