package com.clevel.selos.integration.brms.model;

public enum BRMSField {
    APPLICATION_NUMBER("applicationNumber"),
    PROCESS_DATE("processDate"),
    APP_IN_DATE("App in Date"),
    EXPECTED_SUBMIT_DATE("Expected Submit Date"),
    CUSTOMER_ENTITY("Customer Entity"),
    EXISTING_SME_CUSTOMER("Existing SME Customer"),
    SAME_SET_OF_BORROWER("Same set of borrower"),
    REFINANCE_IN_FLAG("Refinance In flag"),
    REFINANCE_OUT_FLAG("Refinance Out flag"),
    LENDING_REFER_TYPE("Lending Refer Type"),
    BA_FLAG("BA Flag"),
    TOP_UP_BA_FLAG("Top Up BA Flag"),
    SBCG_FLAG("SBCG Flag"),
    AAD_FLAG("AAD Flag"),
    NUMBER_OF_YEAR_FROM_LATEST_FINANCIAL_STATEMENT("Number of year from latest financial statement"),
    NET_WORTH("Net Worth"),
    FINAL_DBR("Final DBR"),
    MONTHLY_INCOME("Monthly Income"),
    BORROWER_GROUP_SALE("Borrower Group Sale"),
    TOTAL_GROUP_SALE("Total Group Sale"),
    EXISTING_GROUP_EXPOSURE("Existing Group Exposure"),
    FINAL_GROUP_EXPOSURE("Final Group Exposure"),
    LG_CAPABILITY("LG Capability"),
    EVER_LG_CLAIM("Ever LG Claim"),
    ABANDON_PROJECT("Abandon Project"),
    PROJECT_DELAY("Project Delay"),
    SUFFICIENT_SOURCE_OF_FUND("Sufficient source of Fund"),
    PRIME_CUSTOMER("Prime Customer"),
    NUM_OF_TOTAL_FACILITY("Num of total facility"),
    NUM_OF_CONTIGENT_FACILITY("Num of contingent facility"),
    NUM_OF_EXISTING_OD("Number of existing OD"),
    NUM_OF_REQUEST_OD("Number of requested OD"),
    NUM_OF_CORE_ASSET("Num of Core Asset"),
    NUM_OF_NON_CORE_ASSET("Num of Non-Core Asset"),
    TOTAL_FIX_ASSET_VALUE("Total Fix Asset Value"),
    EXISTING_OD_LIMIT("Existing O/D limit"),
    TOTAL_COLL_PERCENT_OF_EXPOSURE("Total Coll% of Exposure"),
    TOTAL_WC_REQUIREMENT("Total W/C Requirement"),
    NET_WC_REQUIREMENT_1_25X("Net W/C Requirement (1.25x)"),
    NET_WC_REQUIREMENT_1_5X("Net W/C Requirement (1.5x)"),
    NET_WC_REQUIREMENT_35_PERCENT_OF_SALES("Net W/C Requirement (35% of Sales)"),
    EXISTING_WC_CREDIT_LIMIT_WITH_TMB("Existing W/C credit limit with TMB"),
    EXISTING_CORE_WC_LOAN_CREDIT_LIMIT_WITH_TMB("Existing Core W/C Loan credit limit with TMB"),
    BUSINESS_LOCATION("Business Location"),
    YEAR_IN_BUSINESS("Year in Business"),
    COUNTRY_OF_REGISTRATION("Country of Registration"),
    TRADE_CHEQUE_RETURN_PERCENT("Trade Cheque Return %"),
    COLLATERAL_POTENTIAL_FOR_PRICING("Collateral Potential for pricing"),
    RELATIONSHIP_TYPE("Relationship Type"),
    REFERENCE("Reference"),
    NATIONALITY("Nationality"),
    NUMBER_OF_MONTH_FROM_LAST_SET_UP_DATE("Number of month from Last set up date"),
    NEW_QUALITATIVE("New Qualitative"),
    BOT_CLASS("BOT Class"),
    NEXT_REVIEW_DATE("Next Review Date"),
    NEXT_REVIEW_DATE_FLAG("Next Review Date Flag"),
    EXTENDED_REVIEW_DATE("Extended Review Date"),
    EXTENDED_REVIEW_DATE_FLAG("Extended Review Date Flag"),
    RATING_FINAL("RATING_FINAL"),
    UNPAID_FEE_INSURANCE_PREMIUM("Unpaid Fee / Unpaid Insurance Premium"),
    CLAIMED_LG("Claimed LG"),
    CREDIT_WORTHINESS("Credit Worthiness"),
    KYC("KYC"),
    SPOUSE_ID("Spouse ID"),
    SPOUSE_RELATIONSHIP_TYPE("Spouse Relationship Type"),
    PERSONAL_ID("Personal ID"),
    AGE("Age"),
    MARRIAGE_STATUS("Marriage Status"),
    ACTIVE_FLAG("Active Flag"),
    DATA_SOURCE("Data Source"),
    ACCOUNT_REF("Account Ref"),
    CUST_TO_ACCOUNT_RELATIONSHIP("Cust to account relationship"),
    TDR_FLAG("TDR Flag"),
    NUMBER_OF_MONTH_PRINCIPAL_AND_INTEREST_PAST_DUE("Number of month principal and interest past due"),
    NUMBER_OF_MONTH_PRINCIPAL_AND_INTEREST_PAST_DUE_OF_TDR_ACCOUNT("Number of month principal and interest past due of TDR account"),
    NUMBER_OF_DAY_PRINCIPAL_PAST_DUE("Number of day principal past due"),
    NUMBER_OF_DAY_INTEREST_PAST_DUE("Number of day interest past due"),
    CARD_BLOCK_CODE("Card Block Code"),
    NCB_FLAG("NCB Flag"),
    NCB_ACCOUNT_STATUS("NCB Account Status"),
    TMB_BANK_FLAG("TMB Bank Flag"),
    NCB_NPL_FLAG("NCB NPL Flag"),
    CREDIT_AMOUNT_AT_FIRST_NPL_DATE("Credit Amount at first NPL date"),
    NCB_TDR_FLAG("NCB TDR Flag"),
    CURRENT_PAYMENT_PATTERN("Current Payment Pattern"),
    SIX_MONTHS_PAYMENT_PATTERN("6M Payment Pattern"),
    TWELVE_MONTHS_PAYMENT_PATTERN("12M Payment Pattern"),
    OVER_DUE_31_TO_60_DAYS_WITHIN_LAST_12_MONTHS("Over Due 31-60 days within last 12 months"),
    OVER_LIMIT_WITHIN_LAST_6_MONTHS("Over Limit within last 6 months"),
    NUMBER_OF_SEARCH_IN_LAST_6_MONTHS("Number of search in last 6 months"),
    NUMBER_OF_DAYS_NCB_CHECK("Number of days NCB check"),
    RISK_CODE_WITH_FULLY_IDENTIFY_MATCHED("Risk Code with fully identify matched"),
    RISK_CODE_WITH_SOME_IDENTIFY_MATCHED("Risk Code with some identify matched"),
    UTILIZATION_PERCENT("Utilization %"),
    SWING_PERCENT("Swing %"),
    AVG_LAST_6_MONTHS_INFLOW_LIMIT("Avg. L6m Inflow/Limit"),
    NUM_OF_TRANSACTION_INFLOW_OUTFLOW("No. of Transaction (Inflow&Outflow)"),
    CHEQUE_RETURN_TIMES("Cheque Return (Times)"),
    OD_OVER_LIMIT_DAYS("OD Over Limit (Days)"),
    CASH_INFLOW("Cash Inflow"),
    MAIN_ACCOUNT_FLAG("Main Account Flag"),
    HIGHEST_INFLOW_FLAG("Highest Inflow Flag"),
    TMB_ACCOUNT_FLAG("TMB Account Flag"),
    EXCLUDE_INCOME_FLAG("Exclude Income Flag"),
    BUSINESS_CODE_RUNNING_NUMBER("Business code running number"),
    BUSINESS_CODE("Business code"),
    NEGATIVE_FLAG("Negative Flag"),
    HIGH_RISK_FLAG("High Risk Flag"),
    PRODUCT_GROUP("Product Group"),
    MAX_CREDIT_LIMIT_BY_COLLATERAL("Max Credit Limit by Collateral"),
    TOTAL_PROPOSED_CREDIT_LIMIT("Total Proposed Credit Limit"),
    PRODUCT_PROGRAM("Product Program"),
    CREDIT_FACILITY_TYPE("Credit Facility Type"),
    CREDIT_LIMIT("Credit Limit"),
    TENOR("Tenor"),
    GUARANTEE_TYPE("Guarantee Type"),
    LOAN_PURPOSE("Loan Purpose"),
    COLLATERAL_POTENTIAL("Collateral Potential"),
    COLLATERAL_TYPE("Collateral Type"),
    APPRAISAL_FLAG("Appraisal Flag"),
    AAD_COMMENT("AAD Comment"),
    PERCENT_APPRAISAL_VALUE_OF_BUILDING_WITH_OWNERSHIP_DOC("%Appraisal Value of Building with ownership doc"),
    LENGTH_OF_APPRAISAL_MONTHS("Length of Appraisal (months)"),
    DAY_ANNUAL_REVIEW_OVERDUE("Day Annual Review Overdue"),
    MAX_WC_CREDIT_LIMIT("Max WC Credit Limit"),
    TOTAL_REQUESTED_WC_CREDIT_LIMIT("Total Requested WC Credit Limit"),
    MAX_CORE_WC_LOAN_LIMIT("Max Core WC Loan Limit"),
    TOTAL_REQUESTED_CORE_WC_LOAN_CREDIT_LIMIT("Total Requested Core WC Loan credit limit"),
    TOTAL_REQUESTED_OD_CREDIT_LIMIT("Total Requested OD credit limit"),
    TOTAL_TCG_GUARANTEE_AMOUNT("Total TCG Guarantee Amount"),
    NUMBER_OF_INDV_GUARANTOR("Number Of Individual Guarantor"),
    NUMBER_OF_JURIS_GUARANTOR("Number Of Juristic Guarantor"),
    TOTAL_MORTGAGE_VALUE("Total Mortgage Value"),
    NUMBER_OF_REDEEM_TRANSACTION("Number Of Redeem Transaction");

    String value;

    BRMSField(String value) {
        this.value = value;
    }

    public String value() {
        return this.value;
    }
}
