
package com.tmb.common.data.eaisearchcustomeraccount;

import com.tmb.common.data.requestsearchcustomeraccount.ReqSearchCustomerAccount;
import com.tmb.common.data.responsesearchcustomeraccount.ResSearchCustomerAccount;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 */
@WebService(name = "EAISearchCustomerAccount", targetNamespace = "http://data.common.tmb.com/EAISearchCustomerAccount/")
public interface EAISearchCustomerAccount {


    /**
     * @param requestData
     * @return returns com.tmb.common.data.responsesearchcustomeraccount.ResSearchCustomerAccount
     */
    @WebMethod(action = "searchCustomerAccount")
    @WebResult(name = "responseData", targetNamespace = "")
    @RequestWrapper(localName = "searchCustomerAccount", targetNamespace = "http://data.common.tmb.com/EAISearchCustomerAccount/", className = "com.tmb.common.data.eaisearchcustomeraccount.SearchCustomerAccount")
    @ResponseWrapper(localName = "searchCustomerAccountResponse", targetNamespace = "http://data.common.tmb.com/EAISearchCustomerAccount/", className = "com.tmb.common.data.eaisearchcustomeraccount.SearchCustomerAccountResponse")
    public ResSearchCustomerAccount searchCustomerAccount(
            @WebParam(name = "requestData", targetNamespace = "")
            ReqSearchCustomerAccount requestData);

}
