
package com.clevel.selos.integration.brms.service.fullapplicationUnderwritingrules;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */

@WebServiceClient(name = "DecisionServiceSE_Full_Application_UWS_Flow", targetNamespace = "http://www.ilog.com/rules/DecisionService", wsdlLocation = "http://stmbrmsred1:9080/DecisionService/ws/SE_Full_Application_UWS_RuleApp/1.0/SE_Full_Application_UWS_Flow?WSDL")
public class DecisionServiceSEFullApplicationUWSFlow_Service
        extends Service {

    private final static URL DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_WSDL_LOCATION;
    private final static WebServiceException DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_EXCEPTION;
    private final static QName DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_QNAME = new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSE_Full_Application_UWS_Flow");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://stmbrmsred1:9080/DecisionService/ws/SE_Full_Application_UWS_RuleApp/1.0/SE_Full_Application_UWS_Flow?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_WSDL_LOCATION = url;
        DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_EXCEPTION = e;
    }

    public DecisionServiceSEFullApplicationUWSFlow_Service() {
        super(__getWsdlLocation(), DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_QNAME);
    }

    public DecisionServiceSEFullApplicationUWSFlow_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_QNAME);
    }

    public DecisionServiceSEFullApplicationUWSFlow_Service(URL wsdlLocation) {
        super(wsdlLocation, DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_QNAME);
    }

    public DecisionServiceSEFullApplicationUWSFlow_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_QNAME);
    }

    public DecisionServiceSEFullApplicationUWSFlow_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DecisionServiceSEFullApplicationUWSFlow_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns DecisionServiceSEFullApplicationUWSFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEFullApplicationUWSFlow getDecisionServiceSOAPstmbrmsred1() {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEFullApplicationUWSFlow.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DecisionServiceSEFullApplicationUWSFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEFullApplicationUWSFlow getDecisionServiceSOAPstmbrmsred1(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEFullApplicationUWSFlow.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_EXCEPTION != null) {
            throw DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_EXCEPTION;
        }
        return DECISIONSERVICESEFULLAPPLICATIONUWSFLOW_WSDL_LOCATION;
    }

}
