
package com.clevel.selos.integration.brms.service.standardpricing.feerules;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DecisionServiceSE_Standard_Pricing_Fee_Flow", targetNamespace = "http://www.ilog.com/rules/DecisionService", wsdlLocation = "file:/C:/Users/Chai/Desktop/BRMS_WSDL/4.wsdl")
public class DecisionServiceSEStandardPricingFeeFlow_Service
    extends Service
{

    private final static URL DECISIONSERVICESESTANDARDPRICINGFEEFLOW_WSDL_LOCATION;
    private final static WebServiceException DECISIONSERVICESESTANDARDPRICINGFEEFLOW_EXCEPTION;
    private final static QName DECISIONSERVICESESTANDARDPRICINGFEEFLOW_QNAME = new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSE_Standard_Pricing_Fee_Flow");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://stmbrmsred1:9080/DecisionService/ws/SE_Standard_Pricing_Fee_RuleApp/1.0/SE_Standard_Pricing_Fee_Flow?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DECISIONSERVICESESTANDARDPRICINGFEEFLOW_WSDL_LOCATION = url;
        DECISIONSERVICESESTANDARDPRICINGFEEFLOW_EXCEPTION = e;
    }

    public DecisionServiceSEStandardPricingFeeFlow_Service() {
        super(__getWsdlLocation(), DECISIONSERVICESESTANDARDPRICINGFEEFLOW_QNAME);
    }

    public DecisionServiceSEStandardPricingFeeFlow_Service(URL wsdlLocation) {
        super(wsdlLocation, DECISIONSERVICESESTANDARDPRICINGFEEFLOW_QNAME);
    }

    public DecisionServiceSEStandardPricingFeeFlow_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DecisionServiceSEStandardPricingFeeFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEStandardPricingFeeFlow getDecisionServiceSOAPstmbrmsred1() {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEStandardPricingFeeFlow.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DecisionServiceSEStandardPricingFeeFlow
     */
    @WebEndpoint(name = "DecisionServiceSOAPstmbrmsred1")
    public DecisionServiceSEStandardPricingFeeFlow getDecisionServiceSOAPstmbrmsred1(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ilog.com/rules/DecisionService", "DecisionServiceSOAPstmbrmsred1"), DecisionServiceSEStandardPricingFeeFlow.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DECISIONSERVICESESTANDARDPRICINGFEEFLOW_EXCEPTION!= null) {
            throw DECISIONSERVICESESTANDARDPRICINGFEEFLOW_EXCEPTION;
        }
        return DECISIONSERVICESESTANDARDPRICINGFEEFLOW_WSDL_LOCATION;
    }

}
